### PR TITLE
Update path to doctest

### PR DESCRIPTION
**Pull request by mohamedhayibor**
Change var doctest = require('../lib/doctest');  to var doctest = require('../src/doctest');

### CODE REVIEW

**Comment by Widdershin** [comment]
Hi! Thanks for opening this pull request.

I'm confused about what this change achieves. When markdown-doctest is installed, I think the src directory isn't included. So I'm not sure if this would work.

What do you think?

**Comment by mohamedhayibor** [comment]
Hi,
You are totally right. My bad, I didn't realize that I was in the bin folder.
I will probably think twice before submitting a pr in the future.

**Comment by Widdershin** [comment]
Hey, that's totally fine :smile: 

The last thing I would want to do is discourage you from making future pull requests.

Can I offer you some feedback for your next pull request?

**Comment by mohamedhayibor** [comment]
Definitely, I consider myself a total noob, ready to do anything to get some massive improvements and hopefully help others in the process. Thanks in advance.

**Pull request closed without merging**
